config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  
  root 'work_orders#schedule'
  resources :work_orders
  get 'schedule', to: 'work_orders#schedule'
  get 'archive', to: 'work_orders#archive'
  
  resources :client do
    get 'schedule'
    get 'archive'
  end
  resources :permits
  resources :printing_instructions
  resources :presort_informations
  

end

app/models/presort_information.rb
class PresortInformation < ActiveRecord::Base
    belongs_to :error_record_handling
    belongs_to :deduping_instructions
    belongs_to :work_order
    belongs_to :permit
    belongs_to :mailing_specs
    belongs_to :mail_class
    belongs_to :sortation
    belongs_to :labels
    belongs_to :piece_type
    belongs_to :postage_type
    validates_inclusion_of :suppression, :in => [true, false]
    validates_inclusion_of :dropship, :in => [true, false]
    accepts_nested_attributes_for :error_record_handling, :deduping_instructions, :mailing_specs, :permit
end

app/controllers/presort_informations_controller.rb
class PresortInformationsController < ApplicationController

  def new
  end

end

app/views/presort_informations/_form.html.erb
<%= f.fields_for :presort_information, PresortInformation.new do |ff| %>
<legend>Mailing</legend>
      <div class="row-fluid">
        <div class="col-md-6">
          <div class="col-md-6">
            <div class="form-group">
              <%= ff.label :Mail_Class, class: "control-label" %>
              <%= ff.collection_select(:mail_class_id, MailClass.all, :id, :name, {:prompt => true}, {:class => "form-control"})%>
  
              <%= ff.label :Piece_Type, class: "control-label" %>
              <%= ff.collection_select(:piece_type_id, PieceType.all, :id, :name, {:prompt => true}, {:class => "form-control"})%> 
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= ff.label :Postage_Type, class: "control-label" %>
              <%= ff.collection_select(:postage_type_id, PostageType.all, :id, :name,  {:prompt => true}, {:class => "form-control"}) %>
  
              <%= ff.label :Sortation, class: "control-label" %>
              <%= ff.collection_select(:sortation_id, Sortation.all, :id, :name,  {:prompt => true}, {:class => "form-control"}) %>
            </div>  
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= ff.label :Suppression?, class: "control-label" %>
              <%= ff.label :suppression, "Yes", :value => "true", class: "control-label"  %>
              <%= ff.radio_button :suppression, true %>
              <%= ff.label :suppression?, "No", :value => "false", class: "control-label" %>
              <%= ff.radio_button :suppression, false, :checked => true%>
            </div>
            <div class="form-group">
              <%= ff.label :Deduping_Instructions, class: "control-label" %>
              <%= ff. collection_select(:deduping_instructions_id, DedupingInstructions.all, :id, :name, {:prompt => true}, {:class => "form-control"}) %>
            </div>
            <div class="form-group">
              <%= ff.label :Error_Handling, class: "control-label" %>
              <%= ff.collection_select(:error_record_handling_id, ErrorRecordHandling.all, :id, :name, {:prompt => true}, {:class => "form-control"}) %>
            </div>            
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= ff.label :Drop_ship?, class: "control-label" %>
              <%= ff.label :Drop_ship, "Yes", :value => "true", class: "control-label"  %>
              <%= ff.radio_button :dropship, true %>
              <%= ff.label :Drop_Ship?, "No", :value => "false", class: "control-label" %>
              <%= ff.radio_button :dropship, false, :checked => true%>
            </div>
            <div class="form-group">
              <%= ff.label :Dropship_Location, class: "control-label" %>
              <%= ff.text_field :dropshipLocation, class: "form-control" %>
            </div>

          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= ff.label :Processing_notes, class: "control-label" %>
              <%= ff.text_area :processing_notes, class: "form-control", rows: 1 %>              
            </div>
          </div>

        </div>
        </div>
        <div class="col-md-6">
          <fieldset>
            <legend>Mailing Specs</legend>
              <%= ff.fields_for :mailing_specs, MailingSpecs.new do |fff| %>
             <div class="col-md-3">
                <div class="form-group">
                  <%= fff.label :Height, class: "control-label"%>
                  <%= fff.text_field :height, class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= fff.label :Sample_Size, class: "control-label"%>
                  <%= fff.text_field :sampleSize, placeholder: "# in one inch", class: "form-control" %>
                </div>
             </div>
              <div class="col-md-3">
                <div class="form-group">
                  <%= fff.label :Width, class: "control-label"%>
                  <%= fff.text_field :width, class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= fff.label :Sample_Weight , class: "control-label"%>
                  <%= fff.text_field :weightOfSample, class: "form-control" %>
                </div>
              </div>
              <% end %>
          </fieldset>
          <fieldset>
            <legend>Permit</legend>
            <% available_permits = Client.find_by(params[:client_number]).permits %>
            <% available_permits << Permit.find_by(permitHolder: "Mail Marketing") if Permit.find_by(permitHolder: "Mail Marketing") %>
            <div class="row-fluid" id="Permit-row">
              <div class= "col-md-5">
                <div class="form-group">
                <%= ff.collection_select(:permit_id, available_permits, :id, :display_name, {:prompt => "Select Permit"}, {:class => "form-control"}) %>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <%= link_to "New Permit", new_permit_path, id: "new_permit", remote: true, class: "btn btn-default" %>
                </div>
              </div>
            </div>
            

              <div class="col-md-5">
                <div class="form-group">
                  <%= label_tag :checkbox, "Client is mail owner", class: "control-label" %>
                  <%= check_box_tag("Client is mail owner",  class: "checkbox-inline") %>
                </div>                
              </div>

          </fieldset>
      </div>
    <% end %>

app/views/presort_informations/new.js.erb
$('.presort-information').append( '<%= j render("presort_informations/form") %>' );


/*
$('#general-info-hidden').html($('#general-info-partial').html());
$('#general-info-partial').html('');

$('.foo').click(function(){
    $('#general-info-partial').html($('#general-info-hidden').html());
});



foo = 'bar';
document.getElementById('foo').innerHtml = 'fomse code';

$('.foo').html('foo');
*/