config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  
  root 'work_orders#schedule'
  resources :work_orders
  get 'schedule', to: 'work_orders#schedule'
  get 'archive', to: 'work_orders#archive'
  
  resources :client do
    get 'schedule'
    get 'archive'
  end
  resources :permits
  resources :printing_instructions
  resources :presort_informations
  

end

app/models/work_order.rb
class WorkOrder < ActiveRecord::Base
  belongs_to :client
  belongs_to :project_type
  belongs_to :status
  belongs_to :labels
  belongs_to :contact
  belongs_to :processor, class_name: 'User'
  has_one :rep, through: :client, class_name: 'User'
  has_one :presort_information
  has_one :printing_instructions
  has_one :production_details
  validates_presence_of :client_id
  validates_presence_of :dueDate
  validates_presence_of :number
  validates_presence_of :project_type_id
  validates_presence_of :monthlySequenceNumber
  validates_presence_of :status_id
  validates_format_of :number, with: /(?:00[1-9]|0[1-9]\d|[1-9]\d\d)\d{2}(?:0[1-9]|1[0-2])-(?:00[1-9]|0[1-9]\d|[1-9]\d\d)/
  validates_format_of :monthlySequenceNumber,
                      with: /(?:00[1-9]|0[1-9]\d|[1-9]\d\d)/
  validates :printing_instructions, presence: true, if: :printing_componant?, on: :create
  validates :presort_information, presence: true, if: :mailing_componant?, on: :create
  accepts_nested_attributes_for :presort_information,
                                :printing_instructions,
                                :production_details

  before_validation :set_monthly_sequence_number,
                    :set_workorder_number,
                    on: :create,
                    unless: @number

  def set_workorder_number
    set_monthly_sequence_number
    self.number = "#{ client.clientnumber }#{ month_and_year_string }-#{ monthlySequenceNumber }" if client
  end

  def display_number
    number[0..2] + '-' + number[5..6] + '-' + number[-3, 3]
  end

  def display_date
    dueDate.strftime('%D')
  end

  def self.schedule
    WorkOrder.joins(:status).where.not(statuses: { description: ['Delete', 'Mailed']}).order(:dueDate)
  end

  def active?
    if status.description == 'Active'
      true
    else
      false
    end
  end

  def in_house?
    if status.description == 'Active' || status.description == 'Completed' || status.description == 'On Hold'
      true
    else
      false
    end
  end

  def mailing_componant?
    project_type.mailing if project_type
  end

  def printing_componant?
    project_type.printing if project_type
  end

  private

    def set_monthly_sequence_number
      self.monthlySequenceNumber = next_sequence_number
    end

    def created_this_month
      WorkOrder.where(created_at: Time.now.beginning_of_month..Time.now.end_of_month).count
    end

    def next_sequence_number
      '%03d' % (created_this_month + 1)
    end

    def month_and_year_string
      "#{Date.today.year.to_s[-2, 2]}#{'%02d' % Date.today.month.to_s}"
    end
end

app/controllers/work_orders_controller.rb
# Controller for central object in system
# Most things will go through here
class WorkOrdersController < ApplicationController
  before_action :set_workorder, only: [:show, :destroy, :edit, :update]

  def index
    redirect_to schedule_path
  end

  def schedule
    @workorders = WorkOrder.schedule
  end

  def archive
    @workorders = WorkOrder.order(:created_at).reverse_order
  end

  def new
    client = Client.find_by(clientnumber: params[:client_number])
    if client
      @workorder = WorkOrder.new(client: client)
      @workorder.set_workorder_number
    else
      redirect_to root_path, alert: 'No Client Exists with that number'
    end
  end

  def create
    @workorder = WorkOrder.new(workorder_params)
    @workorder.status = Status.find_by(description: 'Active')
    respond_to do |format|
      if @workorder.save
        format.html do
          redirect_to @workorder,
                      notice: 'Work Order was successfully created.'
        end
        format.json { render :show, status: :created, location: @workorder }
      else
        format.html { render :new }
        format.json do
          render json: @workorder.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end
  
  def update
    respond_to do |format|
      if @workorder.update_attributes(workorder_params)
        format.html { redirect_to(@workorder, notice: 'Successfully edited work order.') }
        format.json { respond_with_bip(@workorder) }
      else
        format.html { render :action => "edit"}
        format.json { respond_with_bip(@workorder) }
      end
    end
  end
  
  def show
  end

  def edit
  end

  def destroy
    @workorder.status.description = 'Deleted'
    respond_to do |format|
      format.js { @workorder.status.description = 'Deleted' }
    end
  end

  private

  def set_workorder
    @workorder = WorkOrder.find(params[:id])
  end

  def workorder_params
    params.require(:work_order).permit!
  end
end

app/helpers/work_order_helper.rb
module WorkOrderHelper
    
    def append_client(client_id)
      "for " + Client.find(client_id).name
    end
    
end

app/views/work_orders/_form.html.erb
<%= form_for(@workorder) do |f| %>
  <% if @workorder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workorder.errors.count, "error") %> prohibited this workorder from being saved:</h2>
      <ul>
      <% @workorder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <fieldset id="general-info-partial">
    <%=render("genInfo", f: f)%>
  </fieldset>
  <fieldset id="presort-information-partial">
    <%=render("presort_informations/form",  f: f)%>
  </fieldset>
  <div class="col-md-6">
    <fieldset id="printing-information-partial">
    <%=render("printing_instructions/form", f: f)%>
    </fieldset>
  </div>
  <fieldset id="production-details-partial">
    <%=render("production_details/form", f: f) %>
  </fieldset>
  <%= f.hidden_field(:number, :value => @workorder.number) %>
  <%= f.hidden_field(:client_id, :value => @workorder.client_id) %>
  <input type="submit" value="Submit" class="btn btn-default">
<% end %>

<div id="hidden-general-info" class="hidden"></div>

<div id="hidden-presort-information" class="hidden"></div>

<div id="hidden-printing-information" class="hidden"></div>

app/views/work_orders/_genInfo.html.erb
<legend>General</legend>
    <div class="col-md-12">
      <div class="col-md-3">
        <div class="form-group">
          <%= f.label :Job_Title, class: "control-label" %>
          <%= f.text_field :title, class:"form-control" %>
        </div>
  
        <div class="form-group">
          <%= f.label :Project_Type, class: "control-label" %>
          <%= f.collection_select(:project_type_id, ProjectType.all, :id, :name, {:prompt => true}, {:class => "form-control"}) %>
        </div>
      </div>
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :Rep, class: "control-label" %>
        <%= f.text_field :rep, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :Labels, class: "control-label" %>
        <%= f.collection_select(:labels_id, Labels.all, :id, :name, {:prompt => true}, {:class => "form-control"}) %>
      </div>
    </div>
    <div class="col-md-3">
      <div class= "form-group">
          <%= f.label :Due_Date, class: "control-label" %>
          <%= f.text_field :dueDate, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :Project_Description, class: "control-label" %>
        <%= f.text_area :projectDescription,  class: "form-control" %>
      </div>
    </div>
 </div>

app/views/work_orders/archive.html.erb
<% params[:client_id] ? provide(:for," " + append_client(params[:client_id]) + " "): provide(:for, " ") %>
<div class="page-header">
    <h1>Archived Work Orders 
    <%= append_client(params[:client_id]) if params[:client_id] %></h1>
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Work Order Number</th>
            <th>Client</th>
            <th>Description</th>
            <th>Quantity</th>
            <th>Due</th>
        </tr>
    </thead>
    
    <tbody>
        <% @workorders.each do |workorder| %>
        <tr>
            <td><%=workorder.number%></td>
            <td><%=workorder.client.name%></td>
            <td><%=workorder.projectDescription%></td>
            <td><%=workorder.quantity%></td>
            <td><%=workorder.dueDate%></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/work_orders/edit.html.erb
<%provide(:for,"ing Work Order " + @workorder.number + " ")%>

app/views/work_orders/new.html.erb
<%provide(:for," Work Order " + @workorder.display_number + " ")%>
<div class="page-header">
    <h1>Creating Work Order 
    <%=@workorder.display_number %> for <%= @workorder.client.name %>
    </h1>
</div>
<%= render 'form' %>

app/views/work_orders/schedule.html.erb
<% params[:client_id] ? provide(:for," " + append_client(params[:client_id]) + " "): provide(:for, " ") %>
<div class="page-header">
    <h1>Schedule
    <%=  append_client(params[:client_id]) if params[:client_id] %>
    </h1>
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Work Order Number</th>
            <th>Title</th>
            <th>Client</th>
            <th>Description</th>
            <th>Quantity</th>
            <th>Due</th>
            <th>Status</th>
        </tr>
    </thead>
    
    <tbody>
        <% @workorders.each do |workorder| %>
            <tr class = "<%="success" if workorder.status.description == "Completed"%>">
                <td><h4><%=link_to(workorder.display_number,work_order_path(workorder))%></h4></td>
                <td><%=workorder.title%></td>
                <td><%=workorder.client.name%></td>
                <td><%=workorder.projectDescription%></td>
                <td><%=workorder.quantity%></td>
                <td><%= best_in_place workorder, :dueDate, :as => :date, :display_as => :display_date %></td>
                <td><%= best_in_place workorder, :status_id, :as => :select, :collection => Status.status_id_collection, :class => "status" %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/work_orders/show.html.erb
<%provide(:for,"ing Work Order " + @workorder.display_number + " ")%>

<div class="page-header">
    <div class="row">
        <div class="col-md-6">
            <h1>Work Order: <%=@workorder.display_number%> <small>Client: <%=@workorder.client.name%></small></h1>
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-3">
            <h3>Rep:<small> test rep</small></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <h2><%=@workorder.title%></h2>
        </div>
        <div class="col-md-4">
            <h3> Project Type: <%=@workorder.project_type.name%></h3>
        </div>
        <div class="col-md-4">
            <% if @workorder.dueDate > Date.today %>
                <h3>Due: <%=@workorder.dueDate.strftime("%A %B %d, %Y")%></h3>
            <% else %>
                <h3 class="text-danger">Due: <%=@workorder.dueDate.strftime("%A %B %d, %Y")%></h3>
            <% end %>
        </div>
    </div>
</div>
<fieldset id="general-info">
    
</fieldset>
<% if @workorder.mailing_componant? %>
    <fieldset id="presort-information">
        
    </fieldset>
<%end%>
<% if @workorder.printing_componant? %>
    <fieldset id="printing-information">
        
    </fieldset>
<%end%>
<fieldset id="production-information">
    
</fieldset>