config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  
  root 'work_orders#schedule'
  resources :work_orders
  get 'schedule', to: 'work_orders#schedule'
  get 'archive', to: 'work_orders#archive'
  
  resources :client do
    get 'schedule'
    get 'archive'
  end
  resources :permits
  resources :printing_instructions
  resources :presort_informations
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
    validates_presence_of :address1, :city, :state, :zip
    validates_uniqueness_of :address1, scope: [:address2, :city, :state]
    
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :contacts
  has_many :addresses, through: :contacts
  has_many :permits
  has_many :work_orders
  validates :clientnumber, format: { with: /\A\d{3}\z/ },
                           length: { is: 3 }

  belongs_to :rep, class_name: 'User'
  belongs_to :default_processor, class_name: 'User'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    belongs_to :client
    belongs_to :address
    validates_presence_of :client, :name, :address
    validates_uniqueness_of :name, scope: [:client_id]
    
    before_save :check_for_existing_address
    
    
    protected
    
        def check_for_existing_address
            if self.address
                self.address = Address.find_or_create_by(address1: self.address.address1,
                                                         address2: self.address.address2,
                                                         city: self.address.city,
                                                         state: self.address.state)
            end
        end
end

app/models/insert.rb
class Insert < ActiveRecord::Base
        has_many :production_detail_inserts
        validates :machine, :hand, :inclusion => {:in => [true, false]}
        validates_presence_of :description
end

app/models/labels.rb
class Labels < ActiveRecord::Base
    validates_presence_of :name
    has_many :work_orders
end

app/models/mail_class.rb
class MailClass < ActiveRecord::Base
    validates_presence_of(:name)
    has_many(:presort_informations)
end

app/models/mailing_specs.rb
class MailingSpecs < ActiveRecord::Base
    validates_uniqueness_of :sampleSize, scope: [:height, :width, :weightOfSample]
    validates_presence_of(:sampleSize)
    validates_presence_of(:width)
    validates_presence_of(:height)
    validates_presence_of(:weightOfSample)
    has_many(:presort_informations)
end

app/models/permit.rb
class Permit < ActiveRecord::Base
    belongs_to :client
    belongs_to :contact
    has_one :address, :through => :contact
    has_many :work_orders, :through => :presort_informations
    has_many :presort_informations
    validates_presence_of :permitHolder, :postOffice, :contact, :permit_number
    
    def display_name
        "#{permit_number} - #{permitHolder}"
    end
end

app/models/piece_type.rb
class PieceType < ActiveRecord::Base
    validates :name, presence: true,
                     uniqueness: true
    has_many :presort_informations
end

app/models/postage_type.rb
class PostageType < ActiveRecord::Base
    validates :name, presence: true,
                     uniqueness: true
    has_many :presort_informations
end

app/models/project_type.rb
class ProjectType < ActiveRecord::Base
    has_many :work_orders
end

app/models/role.rb
class Role < ActiveRecord::Base
    has_many :users
end

app/models/sortation.rb
class Sortation < ActiveRecord::Base
    validates_presence_of :name
    has_many(:presort_informations)
end

app/models/status.rb
class Status < ActiveRecord::Base
    validates_presence_of :description
    has_many :work_orders
    validates_uniqueness_of :description
    
    def self.status_id_collection
        arr = []
        Status.all.each do |status|
            tempArr = []
            tempArr << status.id
            tempArr << status.description
            arr << tempArr
        end
        arr
    end
end

app/models/tab.rb
class Tab < ActiveRecord::Base
    has_many :production_detail_tabs
    validates_presence_of :location, :type
    validates_uniqueness_of :location, scope: :type
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    
    validates_uniqueness_of :email
    validates_presence_of :email
    validates_presence_of :name
    belongs_to :role
    has_many :clients, foreign_key: 'rep_id'
    has_many :processing_tasks, class_name: 'WorkOrder', foreign_key: 'processor_id'
    
    def has_role?(role_sym)
        role.name.underscore.to_sym == role_sym 
    end
    
    def submitted_jobs
        if self.has_role?(:rep)
            WorkOrder.joins(:client).where('clients.rep_id = ?', self.id)
        end
    end
            
end

app/models/work_order.rb
class WorkOrder < ActiveRecord::Base
  belongs_to :client
  belongs_to :project_type
  belongs_to :status
  belongs_to :labels
  belongs_to :contact
  belongs_to :processor, class_name: 'User'
  has_one :rep, through: :client, class_name: 'User'
  has_one :presort_information
  has_one :printing_instructions
  has_one :production_details
  validates_presence_of :client_id
  validates_presence_of :dueDate
  validates_presence_of :number
  validates_presence_of :project_type_id
  validates_presence_of :monthlySequenceNumber
  validates_presence_of :status_id
  validates_format_of :number, with: /(?:00[1-9]|0[1-9]\d|[1-9]\d\d)\d{2}(?:0[1-9]|1[0-2])-(?:00[1-9]|0[1-9]\d|[1-9]\d\d)/
  validates_format_of :monthlySequenceNumber,
                      with: /(?:00[1-9]|0[1-9]\d|[1-9]\d\d)/
  validates :printing_instructions, presence: true, if: :printing_componant?, on: :create
  validates :presort_information, presence: true, if: :mailing_componant?, on: :create
  accepts_nested_attributes_for :presort_information,
                                :printing_instructions,
                                :production_details

  before_validation :set_monthly_sequence_number,
                    :set_workorder_number,
                    on: :create,
                    unless: @number

  def set_workorder_number
    set_monthly_sequence_number
    self.number = "#{ client.clientnumber }#{ month_and_year_string }-#{ monthlySequenceNumber }" if client
  end

  def display_number
    number[0..2] + '-' + number[5..6] + '-' + number[-3, 3]
  end

  def display_date
    dueDate.strftime('%D')
  end

  def self.schedule
    WorkOrder.joins(:status).where.not(statuses: { description: ['Delete', 'Mailed']}).order(:dueDate)
  end

  def active?
    if status.description == 'Active'
      true
    else
      false
    end
  end

  def in_house?
    if status.description == 'Active' || status.description == 'Completed' || status.description == 'On Hold'
      true
    else
      false
    end
  end

  def mailing_componant?
    project_type.mailing if project_type
  end

  def printing_componant?
    project_type.printing if project_type
  end

  private

    def set_monthly_sequence_number
      self.monthlySequenceNumber = next_sequence_number
    end

    def created_this_month
      WorkOrder.where(created_at: Time.now.beginning_of_month..Time.now.end_of_month).count
    end

    def next_sequence_number
      '%03d' % (created_this_month + 1)
    end

    def month_and_year_string
      "#{Date.today.year.to_s[-2, 2]}#{'%02d' % Date.today.month.to_s}"
    end
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Work Order Portal", root_path, id: 'logo', class: "navbar-brand" %>
    </div>
    
    <ul class="nav navbar-nav">
      <li class= "<%= active_tab?(controller_name, action_name, 'Work Orders') ? 'active' + ' dropdown' : 'dropdown' %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Work Orders<span class="caret"></span></a>
            <ul class="dropdown-menu">
             <li><%= link_to "Schedule", schedule_path %> </li> 
             <li><%= link_to "Archive", archive_path %></li>
            </ul>
        </li>
      <li class= "<%= 'active' if active_tab?(controller_name, action_name, 'Clients')%>"><%= link_to "Clients", client_index_path %></li>
    </ul>
    
    <%= form_tag new_work_order_path, :method => "get", class: "navbar-form navbar-left" do %>
      <div class="form-group">
        <%= text_field_tag :client_number, params[:client_number],  class: "form-control", placeholder: "Enter client number"%>
      </div>
      <button type="sumbit" class="btn btn-default">New Work Order</button>
    <% end %>
    
      <% if current_user %>
      <%= link_to "Log-Out", logout_path, method: "delete", class: "navbar-text navbar-right"%>
      <p class="navbar-text navbar-right">Logged in as <%=current_user.name %></p>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign-Up", signup_path %></li>
        <li><%= link_to "Log-In", login_path %></li>
      </ul>
      <% end %>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= params[:action].humanize %><%=(yield :for)%>| Work Order Portal</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render "layouts/header" %>
    <main class="container">
      
      <% if flash[:alert] %>
        <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
      <% end %>
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
      <% end %>
      
      <%= yield %>
      
    </main>
  </body>
</html>